server:
  port: 8989

spring:
  profiles:
    include: oauth,DBLocation


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true
        "[user_sql_comments]": true
        "[highlight_sql]": true
        "[hbm2ddl.auto]": update
    open-in-view: false
    show-sql: true

  #???? ??
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

jwt:
  issuer: pariahs9311@gmail.com
  secret_key: 92808272306E591C
