server:
  port: 8989

spring:
  datasource:
    #mariadb? ??? ????? ?? ???? ????? ????.
    url: jdbc:mariadb://localhost:3306/sample
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  #???? ??? ?? ??
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA? ??? database? dialect ??
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL? ?? ?? ??
        "[user_sql_comments]": true     #SQL?? ? ?? ??
        "[highlight_sql]": true         #SQL? ??
        "[hbm2ddl.auto]": update
        #"[implicit_naming_strategy]": "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy" -> ????? ???? ??? ?? ???? ??? ???
    open-in-view: false
    show-sql: true

  #???? ??
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  servlet:
    multipart:
      max-file-size: 20MB #파일 한개 당 최대 사이즈
      max-request-size: 100MB #요청당 최대 파일 크기